spring:
  profiles:
    include: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com:
      taskagile: DEBUG
    org:
      springframework:
        security: DEBUG
